font_family JetBrainsMonoNL Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0

background #171812
foreground #fcfcfa
cursor #fcfcfa
cursor_text_color #171812
selection_foreground #171812
selection_background #78dce8

color0  #171812
color1  #ff6188
color2  #a9dc76
color3  #ffd866
color4  #78dce8
color5  #ab9df2
color6  #78dce8
color7  #fcfcfa
color8  #4a483e
color9  #ff6188
color10 #a9dc76
color11 #ffd866
color12 #78dce8
color13 #ab9df2
color14 #78dce8
color15 #fcfcfa

enable_audio_bell no
visual_bell_duration 0.0
remember_window_size no
initial_window_width 115c
initial_window_height 25c
scrollback_lines 50000
scrollback_pager /home/stefan/.local/bin/kitty-scrollback-nvim
wheel_scroll_multiplier 5.0
copy_on_select no
strip_trailing_spaces smart
confirm_os_window_close 1
window_padding_width 0
tab_bar_edge top
tab_bar_style powerline
active_tab_foreground #171812
active_tab_background #78dce8
inactive_tab_foreground #c1bec5
inactive_tab_background #2f3028

map ctrl+shift+h show_scrollback
